var johnTopic = [
	[["KEY", "_class"],                 ["VAL", "bot"], ["BOT","johnBot"]],
    [["KEY", "_htmlprefix"],            ["VAL", "john"]],
    [["KEY", "toto"],                   ["VAL", "Wow, such toto"], ["TYPE", "STR"]],
    [["KEY", "enfant"],                 ["VAL", "Non, je n’ai pas d’enfants."], ["TYPE", "STR"]],
    [["KEY", "etude"],                  ["VAL", "J’ai étudié à l’UPMC."], ["TYPE", "STR"]],
    [["KEY", "etudesmanger"],           ["VAL", "La file d’attente pour manger au restaurant universitaire était trop longue, donc j’achetais souvent de la nourriture dans les fast-food proches ou dans un supermarché."], ["TYPE", "STR"]],
    [["KEY", "dernierefoiscollegue"],   ["VAL", "Je l’ai vu ce matin lors d’une réunion concernant l’avenir de la section nouvellement créée dans l’entreprise."], ["TYPE", "STR"]],
    [["KEY", "heureincident"],          ["VAL", "De ce que j’ai entendu, l’incident s’est produit vers 17h30 hier."], ["TYPE", "STR"]],
    [["KEY", "heuredejeuner"],          ["VAL", "Je prends toujours ma pause déjeuner à 11h45 pour être de retour au travail vers 12h30."], ["TYPE", "STR"]],
    [["KEY", "bananesdessert"],         ["VAL", "Vous savez bien que les bananes sont interdites sur le lieu de travail, il est donc normal que le restaurant administratif n’en serve pas."], ["TYPE", "STR"]],
    [["KEY", "quandentreprise"],        ["VAL", "Celà fait maintenant 2 ans que je travaille dans l’entreprise."], ["TYPE", "STR"]],
    [["KEY", "age"],                    ["VAL", "J’ai eu 27 ans la semaine dernière."], ["TYPE", "STR"]],
    [["KEY", "promotion"],              ["VAL", "J’ai reçu ma première promotion il y a 4 mois."], ["TYPE", "STR"]],
    [["KEY", "colleguecoupable"],       ["VAL", "Je ne pense pas que mon collègue soit le coupable, il est bien trop consciencieux pour faire une telle chose. Mais je peux vous assurer qu’il ne s’agit pas de moi non plus."], ["TYPE", "STR"]],
    [["KEY", "renvoi"],                 ["VAL", "Je suis extrèmement déçu par vos accusations."], ["TYPE", "STR"]],
    [["KEY", "secretaire"],             ["VAL", "Le dossier sur lequel je travaille exige des déplacements permanents."], ["TYPE", "STR"]],
    [["KEY", "mentir"],                 ["VAL", "Ah ça non, jamais !"], ["TYPE", "STR"]],
    [["KEY", "contredire"],             ["VAL", "Il préfère probablement accuser à tort pour se sauver."], ["TYPE", "STR"]],
    [["KEY", "colleguementir"],         ["VAL", "Non, il est trop consciencieux pour ça."], ["TYPE", "STR"]],
    [["KEY", "fruitprefere"],           ["VAL", "J’aime beaucoup les fraises."], ["TYPE", "STR"]],
    [["KEY", "mangerbanane"],           ["VAL", "De temps à autre."], ["TYPE", "STR"]],
    [["KEY", "victime"],                ["VAL", "Oui, c’est même elle qui m’a poussé à rejoindre l’entreprise. Quel dommage qu’il lui soit arrivé un tel incident."], ["TYPE", "STR"]],
    [["KEY", "heureincident"],          ["VAL", "Lorsque ça a eu lieu, j’étais en train de travailler sur le dernier dossier."], ["TYPE", "STR"]],
    [["KEY", "coupable"],               ["VAL", "Non, s’il-vous-plait, ne me renvoyez pas !"], ["TYPE", "STR"]],
    [["KEY", "tempslibre"],             ["VAL", "Quand je ne suis pas avec des amis, je joue aux jeux vidéo."], ["TYPE", "STR"]],
    [["KEY", "concierge"],              ["VAL", "Il a dû me confondre avec quelqu’un d’autre"], ["TYPE", "STR"]],
    [["KEY", "entreprise"],             ["VAL", "C’est une opportunité unique pour moi d’en faire partie."], ["TYPE", "STR"]],
    [["KEY", "zimbabwe"],               ["VAL", "Bien évidemment, nous pourrions ainsi enquêter directement sur cette histoire de bananes."], ["TYPE", "STR"]],
    [["KEY", "congepaye"],              ["VAL", "Merci ! Je vais pouvoir partir en vacances au Zimbabwe pour manger enfin des bananes locales."], ["TYPE", "STR"]],
    [["KEY", "moteur"],                 ["VAL", "Je ne pense pas en être encore à ce stade, Monsieur."], ["TYPE", "STR"]],
    [["KEY", "disgrace"],               ["VAL", "Je vais faire de mon mieux pour me resaisir alors !"], ["TYPE", "STR"]],
    [["KEY", "notebook"],               ["VAL", "Si j’utilise le notebook j’ai 17."], ["TYPE", "STR"]],
    [["KEY", "jeuderole"],              ["VAL", "Moi j’suis pas chaud pour le jeu de rôle."], ["TYPE", "STR"]],
    [["KEY", "qualite"],                ["VAL", "Dynamique, travailleur et ouvert d’esprit."], ["TYPE", "STR"]],
    [["KEY", "defaut"],                 ["VAL", "Espiègle et distrait."], ["TYPE", "STR"]],
    [["KEY", "qualitecollegue"],        ["VAL", "Il est sympathique et consciencieux."], ["TYPE", "STR"]],
    [["KEY", "defautcollegue"],         ["VAL", "Il est parfois tellement discret que l’on ne se rend pas compte qu’il travaille efficacement."], ["TYPE", "STR"]],
    [["KEY", "emploiformation"],        ["VAL", "C’est une expérience inoubliable que je rêve de réaliser depuis toujours."], ["TYPE", "STR"]],
    [["KEY", "reducteur"],              ["VAL", "Certes."], ["TYPE", "STR"]],
    [["KEY", "dernierprojet"],          ["VAL", "La réalisation d’un serious game sur le système immunitaire."], ["TYPE", "STR"]],
    [["KEY", "collegue"],               ["VAL", "C’est un honnête homme."], ["TYPE", "STR"]],
    [["KEY", "conserver"],              ["VAL", "Il est tout ce que j’ai."], ["TYPE", "STR"]],
    [["KEY", "projetcollegue"],         ["VAL", "Pourquoi pas, je suis sûr que l’on va bien s’entendre."], ["TYPE", "STR"]],
    [["KEY", "couleur"],                ["VAL", "Rouge."], ["TYPE", "STR"]],
    [["KEY", "film"],                   ["VAL", "The Matrix."], ["TYPE", "STR"]],
    [["KEY", "animal"],                 ["VAL", "Le lapin."], ["TYPE", "STR"]],
    [["KEY", "musique"],                ["VAL", "J’apprécie la Rap musique. T’entends jeune fanatique ?"], ["TYPE", "STR"]],
    [["KEY", "taille"],                 ["VAL", "Environ 180cm."], ["TYPE", "STR"]],
    [["KEY", "poids"],                  ["VAL", "Je pèse 95kg. Mon IMC est légèrement en dessous de la limite supérieure."], ["TYPE", "STR"]],
    [["KEY", "oeil"],                   ["VAL", "J’ai les yeux marrons."], ["TYPE", "STR"]],
    [["KEY", "explication"],            ["VAL", "Je pense que c’était un accident et que le coupable doit s’en vouloir."], ["TYPE", "STR"]],
    [["KEY", "alibi"],                  ["VAL", "J’étais chez moi en train de dormir, j’ai demandé à quelqu’un d’autre de signer pour moi."], ["TYPE", "STR"]]
    [["KEY", "confirmer"],              ["VAL", "Vous pouvez contacter mes parents pour qu’ils vous fassent un mot."], ["TYPE", "STR"]]
];

var bobTopic = [
    [["KEY", "_class"],                 ["VAL", "bot"], ["BOT","bobBot"]],
    [["KEY", "_htmlprefix"],            ["VAL", "bob"]],
    [["KEY", "toto"],                   ["VAL", "Wow, such toto"], ["TYPE", "STR"]],
    [["KEY", "enfant"],                 ["VAL", "Oui, j’ai une fille et un garçon. Chaque matin, ma femme leur prépare leur goûter."], ["TYPE", "STR"]],
    [["KEY", "gouterenfant"],           ["VAL", "Soucieuse de la santé de mes enfants, ma femme mets toujours des fruits dans leur panier pour le goûter."], ["TYPE", "STR"]],
    [["KEY", "gouterbanane"],           ["VAL", "Oui, c’est probable."], ["TYPE", "STR"]],
    [["KEY", "etude"],                  ["VAL", "J’ai étudié aux Arts et Métiers."], ["TYPE", "STR"]],
    [["KEY", "etudesmanger"],           ["VAL", "Je mangeais des choses diverses et variées au restaurant de l’école."], ["TYPE", "STR"]],
    [["KEY", "dernierefoiscollegue"],   ["VAL", "Je l’ai vu ce matin lors d’une réunion concernant l’avenir de la section nouvellement créée dans l’entreprise."], ["TYPE", "STR"]],
    [["KEY", "heureincident"],          ["VAL", "De ce que j’ai entendu, l’incident s’est produit à 13h45 hier."], ["TYPE", "STR"]],
    [["KEY", "heuredejeuner"],          ["VAL", "Il n’y avait pas beaucoup de travail aujourd’hui, j’en ai profité pour manger au restaurant. Je devais y être entre 12h et 13h30."], ["TYPE", "STR"]],
    [["KEY", "bananesdessert"],         ["VAL", "Vous savez bien que les bananes sont interdites sur le lieu de travail, il est donc normal que le restaurant administratif n’en serve pas."], ["TYPE", "STR"]],
    [["KEY", "quandentreprise"],        ["VAL", "Cinq années de bons et loyaux services, Monsieur."], ["TYPE", "STR"]],
    [["KEY", "age"],                    ["VAL", "J’aurai 35 ans dans 2 mois."], ["TYPE", "STR"]],
    [["KEY", "promotion"],              ["VAL", "Ma dernière promotion date d’il y a 1 an."], ["TYPE", "STR"]],
    [["KEY", "colleguecoupable"],       ["VAL", "Etant donné qu’il est encore jeune, il est fort probable qu’il ait oublié un chapitre du règlement intérieur."], ["TYPE", "STR"]],
    [["KEY", "renvoi"],                 ["VAL", "Vous n’avez aucune preuve."], ["TYPE", "STR"]],
    [["KEY", "secretaire"],             ["VAL", "Le dossier sur lequel je travaille exige des déplacements permanents."], ["TYPE", "STR"]],
    [["KEY", "mentir"],                 ["VAL", "Ah ça non, jamais !"], ["TYPE", "STR"]],
    [["KEY", "contredire"],             ["VAL", "Vous préférez croire un novice de l’entreprise ?"], ["TYPE", "STR"]],
    [["KEY", "colleguementir"],         ["VAL", "C’est fort probable, il veut sauver sa peau."], ["TYPE", "STR"]],
    [["KEY", "fruitprefere"],           ["VAL", "Les kiwis bien évidemment."], ["TYPE", "STR"]],
    [["KEY", "mangerbanane"],           ["VAL", "Je suis allergique aux bananes."], ["TYPE", "STR"]],
    [["KEY", "victime"],                ["VAL", "Je l’ai déjà croisée, mais ça s’arrête là."], ["TYPE", "STR"]],
    [["KEY", "heureincident"],          ["VAL", "J’étais en train de prendre ma pause."], ["TYPE", "STR"]],
    [["KEY", "coupable"],               ["VAL", "Oui je l’admets, c’est moi le coupable."], ["TYPE", "STR"]],
    [["KEY", "tempslibre"],             ["VAL", "Je lis, ça me détend."], ["TYPE", "STR"]],
    [["KEY", "concierge"],              ["VAL", "Il a dû me confondre avec quelqu’un d’autre"], ["TYPE", "STR"]],
    [["KEY", "entreprise"],             ["VAL", "Je ne me suis jamais senti aussi bien ici qu’ailleurs."], ["TYPE", "STR"]],
    [["KEY", "zimbabwe"],               ["VAL", "Je préfère rester en France."], ["TYPE", "STR"]],
    [["KEY", "congepaye"],              ["VAL", "Ca tombe bien, ma femme et mes enfants avaient justement envie de partir en vacances."], ["TYPE", "STR"]],
    [["KEY", "moteur"],                 ["VAL", "Merci ! J’espère que je vais bientôt recevoir une augmentation !"], ["TYPE", "STR"]],
    [["KEY", "disgrace"],               ["VAL", "Comment osez-vous ? Avec tout le travail que je fournis…"], ["TYPE", "STR"]],
    [["KEY", "notebook"],               ["VAL", "Ce serait une bonne idée pour géolocaliser le coupable."], ["TYPE", "STR"]],
    [["KEY", "jeuderole"],              ["VAL", "En costume-cravate ? On appelle pas ça une réunion ?"], ["TYPE", "STR"]],
    [["KEY", "qualite"],                ["VAL", "Sérieux, motivé et efficace."], ["TYPE", "STR"]],
    [["KEY", "defaut"],                 ["VAL", "Trop discret et casanier."], ["TYPE", "STR"]],
    [["KEY", "qualitecollegue"],        ["VAL", "Je ne pense pas qu’il ait la moindre qualité."], ["TYPE", "STR"]],
    [["KEY", "defautcollegue"],         ["VAL", "Il est très farceur."], ["TYPE", "STR"]],
    [["KEY", "emploiformation"],        ["VAL", "J’utilise précisément les compétences que j’ai étudiées dans mon travail au quotidien."], ["TYPE", "STR"]],
    [["KEY", "reducteur"],              ["VAL", "Permettez-moi de désapprouver."], ["TYPE", "STR"]],
    [["KEY", "dernierprojet"],          ["VAL", "Le développement d’un jeu mobile dans lequel le joueur devait lancer des bananes sur des singes."], ["TYPE", "STR"]],
    [["KEY", "collegue"],               ["VAL", "Il est sournois et manipulateur."], ["TYPE", "STR"]],
    [["KEY", "conserver"],              ["VAL", "Evidemment, j’ai une femme et des enfants à nourrir !"], ["TYPE", "STR"]],
    [["KEY", "projetcollegue"],         ["VAL", "C’est hors de question ! Il est bien trop insupportable."], ["TYPE", "STR"]],
    [["KEY", "couleur"],                ["VAL", "Vert."], ["TYPE", "STR"]],
    [["KEY", "film"],                   ["VAL", "La planète des singes."], ["TYPE", "STR"]],
    [["KEY", "animal"],                 ["VAL", "Le singe."], ["TYPE", "STR"]],
    [["KEY", "musique"],                ["VAL", "J’aime beaucoup le Melodic death metal."], ["TYPE", "STR"]],
    [["KEY", "taille"],                 ["VAL", "1m95."], ["TYPE", "STR"]],
    [["KEY", "poids"],                  ["VAL", "Je pèse actuellement 80kg. Mais que du muscle !"], ["TYPE", "STR"]],
    [["KEY", "oeil"],                   ["VAL", "Mes yeux sont bleus."], ["TYPE", "STR"]],
    [["KEY", "explication"],            ["VAL", "C’est un complot Illuminati."], ["TYPE", "STR"]],
    [["KEY", "alibi"],                  ["VAL", "J’étais à la machine à café. J’y ai peut-être passé trop de temps par contre..."], ["TYPE", "STR"]]
    [["KEY", "confirmer"],              ["VAL", "Des gens étaient avec moi à la machine à café."], ["TYPE", "STR"]]
];

var johnBot = new BOT_makeBot("johnBot","johnTopic");
var bobBot = new BOT_makeBot("bobBot","bobTopic");
BOT_theBotId		= "johnBot";
BOT_theTopicId		= "johnTopic";